### PR TITLE
Bump xcodeproj to 1.27.0

### PR DESCRIPTION
**Pull request by stephengilroy**
Just a simple bump to the latest xcodeproj. I think you'll need to add the v1.1.2 tag as well once it is merged.

### CODE REVIEW

**Comment by stephengilroy** [comment]
@noahsark769 looks like I can't add you as a reviewer but a really minor bump. Confirmed locally on a pretty complex project I have.

**Comment by noahsark769** [comment]
Nice! Will merge, won't be able to tag until later tonight/tomorrow but will do. Thanks for keeping this alive!

**Comment by stephengilroy-grx** [comment]
Thanks @noahsark769! Appreciate the speedy response 👍

**Comment by noahsark769** [comment]
Added the tag! Thanks again for updating this!

**Pull request merged**
